version: '3'
services:
    db:
        image: "postgres:9"
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_DB=blogdb
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_INITDB_ARGS="--encoding=UTF-8 --locale=ja_JP.UTF-8"
    app:
        image: "myapp/springboot"
        environment:
          - SPRING_PROFILE_ACTIVE=selenium
          - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/uitest
        ports:
          - "8080:8080"
        depends_on: db
    chrome:
        image: "yukinying/chrome-headless-browser-selenium:latest"
        ports:
          - "4444:4444"
        depends_on: app