version: '2'
services:
    db:
        container_name: db
        image: "postgres:9"
        ports:
          - "5433:5432"
        environment:
          - POSTGRES_DB=blogdb
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        networks:
          - app_nw
    app:
        container_name: app
        image: "maruhachi/headless-chrome-selenide:latest"
        environment:
          - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/blogdb
        ports:
          - "8080:8080"
        networks:
          - app_nw
        depends_on: 
          - db
    chrome:
        container_name: chrome
        image: "yukinying/chrome-headless-browser-selenium:latest"
        ports:
          - "4444:4444"
        networks:
          - app_nw
        depends_on:
          - app
networks:
  app_nw:
